version: "3.5"

services:
  django:
    build: .
    command: ./manage.py runserver "0.0.0.0:8000"
    links:
      - postgres:postgres
    volumes:
      - .:/app
    networks:
      - default
    entrypoint: python
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    tty: true

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5